export NEURON_ACTIVATION_THRESHOLD, INTERELEMENT_ACTIVATION_THRESHOLD, INTERELEMENT_WEIGHT_POWER, AVBTREE_ORDER

const NEURON_ACTIVATION_THRESHOLD = 0.95

const INTERELEMENT_ACTIVATION_THRESHOLD = 0.9

const INTERELEMENT_WEIGHT_POWER = 5

const AVBTREE_ORDER = 3